POST http://localhost:5000//api/userUpdation HTTP/1.1
content-type: application/json

{
    "email": "usr2@mail.com",
    "prn_no":"2",
    "clg_id":"CLG2"
}
###


POST http://localhost:5000/api/getUserProfile HTTP/1.1
content-type: application/json

{
    "prn_no":"2",
    "clg_id":"CLG1"
}
###

